name: Build and Publish Memos

on:
  push:
    branches: [ main ]
    paths:
      - 'memos/**'
      - 'notebooks/**'
      - '.github/workflows/build‑memos.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'memos/**'
      - 'notebooks/**'
      - '.github/workflows/build‑memos.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-extra latexmk

    - name: Compile LaTeX memos
      run: |
        mkdir -p docs/memos
        for dir in memos/*/ ; do
          for src in "$dir"/*.tex ; do
            fname=$(basename "$src" .tex)
            latexmk -pdf \
              -jobname="$fname" \
              -output-directory=docs/memos \
              "$src"
          done
        done

    - name: Copy direct PDF uploads
      run: |
        mkdir -p docs/notebooks
        cp notebooks/*.pdf docs/notebooks/ || echo "No uploads to copy"

    - name: Upload PDFs for review
      uses: actions/upload-artifact@v3
      with:
        name: memo-pdfs
        paths: |
          docs/memos/*.pdf
          docs/notebooks/*.pdf

    - name: Prepare Jekyll site
      run: |
        cp docs/_config.yml docs/
        cp docs/index.md docs/

    - name: Commit generated files
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add docs/memos/*.pdf docs/notebooks/*.pdf docs/index.md docs/_config.yml
        git commit -m "rebuild memos & notebooks" || echo "No changes to commit"

    - name: Push to GitHub
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
