name: Build and Publish Memos

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install a basic TeXlive environment
    - name: Install TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-extra latexmk

    # Build all .tex files into PDFs
    - name: Compile LaTeX memos
      run: |
        mkdir -p docs/memos
        for src in memos/*.tex; do
          latexmk -pdf -jobname=$(basename "$src" .tex) -output-directory=docs/memos "$src"
        done

    # Copy Jekyll config and index into docs/
    - name: Prepare Jekyll site
      run: |
        cp docs/_config.yml docs/
        cp docs/index.md docs/

    # Commit built docs back (so Pages can serve them)
    - name: Commit generated PDFs
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add docs/memos/*.pdf docs/index.md docs/_config.yml
        git commit -m "📝 rebuild memos" || echo "No changes to commit"

    - name: Push to GitHub
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
